FROM node:22-alpine

WORKDIR /workspace

RUN npm install -g pnpm@9

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY apps/api/package.json ./apps/api/package.json
COPY apps/web/package.json ./apps/web/package.json
COPY packages/eslint-config/package.json ./packages/eslint-config/package.json
COPY packages/tsconfig/package.json ./packages/tsconfig/package.json
COPY packages/validation/package.json ./packages/validation/package.json

RUN pnpm install

CMD ["sh", "-lc", "tail -f /dev/null"]