export const NOTE_EDITOR_PLACEHOLDER = 'Start writing your note here...';
export const NOTE_EDITOR_WRAPPER_CLASS = 'relative overflow-hidden rounded-3xl border border-border/70 bg-white shadow-[0_20px_60px_rgba(15,23,42,0.06)]';
export const NOTE_EDITOR_HEADER_CLASS = 'border-b border-border/70 bg-gradient-to-r from-slate-50 to-white px-3 py-3 sm:px-4';
export const NOTE_EDITOR_TOOLBAR_CLASS = 'flex items-center gap-1.5 overflow-x-auto pb-1 pr-1 sm:flex-wrap sm:overflow-visible sm:pb-0';
export const NOTE_EDITOR_CONTENT_CLASS = 'prose focus:outline-none max-w-none px-4 py-4 sm:px-5';
export const NOTE_EDITOR_MIN_HEIGHT_CLASS = 'min-h-[240px] sm:min-h-[320px]';
export const NOTE_EDITOR_EDITABLE_CLASS = 'prose prose-sm sm:prose-base focus:outline-none max-w-none min-h-[320px] prose-headings:tracking-tight prose-p:leading-7 prose-li:leading-7 prose-blockquote:border-primary/20 prose-blockquote:text-foreground prose-pre:bg-slate-950 prose-pre:text-slate-50';
export const NOTE_EDITOR_TOOLBAR_BUTTON_CLASS = 'h-10 w-10 rounded-full';
export const NOTE_EDITOR_BUTTON_SPACER_CLASS = 'mx-1 h-6 w-px bg-border';
